version: "3"
services:
  db_postgres:
    image: postgres
    container_name: "emourge_postgres"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgessql

  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    container_name: "emourge_bot"
    depends_on:
      - db_postgres

volumes:
  emourge:
  postgres:
